export const exampleNodes: any = [
  {
    id: "root",
    layoutOptions: {
      "elk.algorithm": "layered",
      "elk.direction": "RIGHT",
      "elk.hierarchyHandling": "INCLUDE_CHILDREN",
      "elk.core.options.EdgeRouting": "ORTHOGONAL",
      "elk.padding": "[top=25,left=25,bottom=25,right=25]",
    },
    children: [
      {
        id: "Hello",
        layoutOptions: {
          "elk.padding": "[top=50,left=50,bottom=50,right=50]",
          "elk.nodeLabels.placement": "[H_LEFT, V_TOP, INSIDE]",
          "elk.hierarchyHandling": "INCLUDE_CHILDREN",
        },
        labels: [
          {
            text: "Hello",
            height: 22,
            width: 49,
          },
        ],
        height: 1,
        width: 1,
        children: [
          {
            id: "Test3",
            layoutOptions: {
              "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
              "elk.hierarchyHandling": "INCLUDE_CHILDREN",
            },
            labels: [
              {
                text: "Test3",
                height: 22,
                width: 49,
              },
            ],
            width: 129,
            height: 52,
          },
          {
            id: "Test4",
            layoutOptions: {
              "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
              "elk.hierarchyHandling": "INCLUDE_CHILDREN",
            },
            labels: [
              {
                text: "Test4",
                height: 22,
                width: 49,
              },
            ],
            width: 129,
            height: 52,
          },
        ],
      },
      {
        id: "Test1",
        layoutOptions: {
          "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
          "elk.hierarchyHandling": "INCLUDE_CHILDREN",
        },
        labels: [
          {
            text: "Test1",
            height: 22,
            width: 49,
          },
        ],
        width: 129,
        height: 52,
      },
      {
        id: "Test2",
        layoutOptions: {
          "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
          "elk.hierarchyHandling": "INCLUDE_CHILDREN",
        },
        labels: [
          {
            text: "Test2",
            height: 22,
            width: 49,
          },
        ],
        width: 129,
        height: 52,
      },
    ],
    edges: [
      {
        id: "Test1/Test2",
        labels: [
          {
            text: "Check",
            layoutOptions: {
              "elk.edgeLabels.placement": "CENTER",
            },
            height: 22,
            width: 49,
          },
        ],
        sources: ["Test1"],
        targets: ["Test2"],
      },
      {
        id: "Test3/Test4",
        labels: [
          {
            text: "Check",
            layoutOptions: {
              "elk.edgeLabels.placement": "CENTER",
            },
            height: 22,
            width: 49,
          },
        ],
        sources: ["Test3"],
        targets: ["Test4"],
      },
    ],
  },
  {
    id: "root",
    layoutOptions: {
      "elk.algorithm": "layered",
      "elk.spacing.nodeNode": "80",
      "elk.contentAlignment": "H_CENTER",
      "elk.direction": "DOWN",
      "elk.layered.spacing.nodeNodeBetweenLayers": "100",
      "org.eclipse.elk.alignment": "CENTER",
      "elk.edgeRouting": "ORTHOGONAL",
      "elk.layered.mergeEdges": true,
      "org.eclipse.elk.edgeRouting": "ORTHOGONAL",
      "elk.layered.spacing.edgeNodeBetweenLayers": "50",
      "elk.alg.layered.options.OrderingStrategy": "NODES_AND_EDGES",
      "elk.layered.crossingMinimization.forceNodeModelOrder": true,
      "elk.layered.nodePlacement.bk.fixedAlignment": "BALANCED",
    },
    children: [
      {
        data: {
          isRoot: true,
          label: "Completes Registration",
          event: "completes_registration",
          name: "completes_registration",
        },
        type: "event-trigger",
        id: "1",
        height: 92,
        width: 360,
      },
      {
        data: {},
        type: "end",
        id: "2",
        height: 42,
        width: 350,
      },
      {
        type: "send-email",
        id: "lehz1d5txedjv11dmid",
        height: 92,
        width: 350,
      },
      {
        type: "wait",
        id: "lehz1gcekn7i869xsn9",
        height: 48,
        width: 280,
      },
      {
        type: "condition",
        id: "lehz1hqyz06d97ravof",
        height: 72,
        width: 360,
      },
      {
        data: {},
        type: "placeholder",
        id: "lehz1hqyz06d97ravof-sink",
        height: 30,
        width: 400,
      },
      {
        type: "wait",
        id: "lehz1k399dgk6pwvpjh",
        height: 48,
        width: 280,
      },
      {
        type: "send-email",
        id: "lehz1lhrhwuttctba7",
        height: 92,
        width: 350,
      },
      {
        type: "wait",
        id: "lehz1my5odjav3xkcqa",
        height: 48,
        width: 280,
      },
      {
        type: "condition",
        id: "lehz1ojd5l6f0f8nfca",
        height: 72,
        width: 360,
      },
      {
        data: {},
        type: "placeholder",
        id: "lehz1ojd5l6f0f8nfca-sink",
        height: 30,
        width: 400,
      },
      {
        type: "send-email",
        id: "lehz1ro4p8ndwch9j2",
        height: 92,
        width: 350,
      },
      {
        type: "wait",
        id: "lehz1t0kb3ai2mx70a7",
        height: 48,
        width: 280,
      },
      {
        type: "send-email",
        id: "lehz1uix4aihgx5r8bi",
        height: 92,
        width: 350,
      },
      {
        type: "wait",
        id: "lehz1wogqa766ri025i",
        height: 48,
        width: 280,
      },
      {
        type: "wait",
        id: "lehz1ygqjovg69f5bzh",
        height: 48,
        width: 280,
      },
      {
        type: "wait",
        id: "lehz20f3bhq2qfni44w",
        height: 48,
        width: 280,
      },
      {
        type: "send-email",
        id: "lehz2271otslpq8u5p",
        height: 92,
        width: 350,
      },
    ],
    edges: [
      {
        data: {
          path: "M 477.5 1790 477.5 1890",
        },
        id: "lehz1d5txedjv11dmid->2",
        source: "lehz1d5txedjv11dmid",
        target: "2",
        sources: ["lehz1d5txedjv11dmid"],
        targets: ["2"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          path: "M 477.5 104 477.5 204",
        },
        id: "1->lehz1gcekn7i869xsn9",
        source: "1",
        target: "lehz1gcekn7i869xsn9",
        sources: ["1"],
        targets: ["lehz1gcekn7i869xsn9"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          duration: 2,
          path: "M 477.5 252 477.5 352",
        },
        id: "lehz1gcekn7i869xsn9->lehz1hqyz06d97ravof",
        source: "lehz1gcekn7i869xsn9",
        target: "lehz1hqyz06d97ravof",
        sources: ["lehz1gcekn7i869xsn9"],
        targets: ["lehz1hqyz06d97ravof"],
        type: "time-wait",
        properties: {},
      },
      {
        data: {
          path: "M 477.5 1598 477.5 1698",
        },
        id: "lehz1hqyz06d97ravof-sink->lehz1d5txedjv11dmid",
        source: "lehz1hqyz06d97ravof-sink",
        target: "lehz1d5txedjv11dmid",
        sources: ["lehz1hqyz06d97ravof-sink"],
        targets: ["lehz1d5txedjv11dmid"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          label: "yes",
          path: "M 477.5 424 477.5 474,477.5 474 187 474,187 474 187 524",
        },
        id: "lehz1hqyz06d97ravof->lehz1k399dgk6pwvpjh",
        source: "lehz1hqyz06d97ravof",
        target: "lehz1k399dgk6pwvpjh",
        sources: ["lehz1hqyz06d97ravof"],
        targets: ["lehz1k399dgk6pwvpjh"],
        type: "yes",
      },
      {
        data: {
          duration: 2,
          path: "M 187 572 187 1376",
        },
        id: "lehz1k399dgk6pwvpjh->lehz1lhrhwuttctba7",
        source: "lehz1k399dgk6pwvpjh",
        target: "lehz1lhrhwuttctba7",
        sources: ["lehz1k399dgk6pwvpjh"],
        targets: ["lehz1lhrhwuttctba7"],
        type: "time-wait",
        properties: {},
      },
      {
        data: {
          path: "M 187 1468 187 1518,187 1518 477.5 1518,477.5 1518 477.5 1568",
        },
        id: "lehz1lhrhwuttctba7->lehz1hqyz06d97ravof-sink",
        source: "lehz1lhrhwuttctba7",
        target: "lehz1hqyz06d97ravof-sink",
        sources: ["lehz1lhrhwuttctba7"],
        targets: ["lehz1hqyz06d97ravof-sink"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          label: "no",
          path: "M 477.5 424 477.5 474,477.5 474 705 474,705 474 705 524",
        },
        id: "lehz1hqyz06d97ravof->lehz1my5odjav3xkcqa",
        source: "lehz1hqyz06d97ravof",
        target: "lehz1my5odjav3xkcqa",
        sources: ["lehz1hqyz06d97ravof"],
        targets: ["lehz1my5odjav3xkcqa"],
        type: "no",
        properties: {},
      },
      {
        data: {
          duration: 2,
          path: "M 705 572 705 672",
        },
        id: "lehz1my5odjav3xkcqa->lehz1ojd5l6f0f8nfca",
        source: "lehz1my5odjav3xkcqa",
        target: "lehz1ojd5l6f0f8nfca",
        sources: ["lehz1my5odjav3xkcqa"],
        targets: ["lehz1ojd5l6f0f8nfca"],
        type: "time-wait",
        properties: {},
      },
      {
        data: {
          path: "M 705 1437 705 1518,705 1518 477.5 1518,477.5 1518 477.5 1568",
        },
        id: "lehz1ojd5l6f0f8nfca-sink->lehz1hqyz06d97ravof-sink",
        source: "lehz1ojd5l6f0f8nfca-sink",
        target: "lehz1hqyz06d97ravof-sink",
        sources: ["lehz1ojd5l6f0f8nfca-sink"],
        targets: ["lehz1hqyz06d97ravof-sink"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          label: "yes",
          path: "M 705 744 705 794,705 794 507.5 794,507.5 794 507.5 844",
        },
        id: "lehz1ojd5l6f0f8nfca->lehz1ro4p8ndwch9j2",
        source: "lehz1ojd5l6f0f8nfca",
        target: "lehz1ro4p8ndwch9j2",
        sources: ["lehz1ojd5l6f0f8nfca"],
        targets: ["lehz1ro4p8ndwch9j2"],
        type: "yes",
      },
      {
        data: {
          label: "no",
          path: "M 705 744 705 794,705 794 902.5 794,902.5 794 902.5 866",
        },
        id: "lehz1ojd5l6f0f8nfca->lehz1t0kb3ai2mx70a7",
        source: "lehz1ojd5l6f0f8nfca",
        target: "lehz1t0kb3ai2mx70a7",
        sources: ["lehz1ojd5l6f0f8nfca"],
        targets: ["lehz1t0kb3ai2mx70a7"],
        type: "no",
        properties: {},
      },
      {
        data: {
          path: "M 507.5 936 507.5 1036",
        },
        id: "lehz1ro4p8ndwch9j2->lehz1uix4aihgx5r8bi",
        source: "lehz1ro4p8ndwch9j2",
        target: "lehz1uix4aihgx5r8bi",
        sources: ["lehz1ro4p8ndwch9j2"],
        targets: ["lehz1uix4aihgx5r8bi"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          duration: 2,
          path: "M 902.5 914 902.5 1058",
        },
        id: "lehz1t0kb3ai2mx70a7->lehz1wogqa766ri025i",
        source: "lehz1t0kb3ai2mx70a7",
        target: "lehz1wogqa766ri025i",
        sources: ["lehz1t0kb3ai2mx70a7"],
        targets: ["lehz1wogqa766ri025i"],
        type: "time-wait",
        properties: {},
      },
      {
        data: {
          duration: 2,
          path: "M 902.5 1106 902.5 1228",
        },
        id: "lehz1wogqa766ri025i->lehz1ygqjovg69f5bzh",
        source: "lehz1wogqa766ri025i",
        target: "lehz1ygqjovg69f5bzh",
        sources: ["lehz1wogqa766ri025i"],
        targets: ["lehz1ygqjovg69f5bzh"],
        type: "time-wait",
        properties: {},
      },
      {
        data: {
          path: "M 507.5 1128 507.5 1228",
        },
        id: "lehz1uix4aihgx5r8bi->lehz20f3bhq2qfni44w",
        source: "lehz1uix4aihgx5r8bi",
        target: "lehz20f3bhq2qfni44w",
        sources: ["lehz1uix4aihgx5r8bi"],
        targets: ["lehz20f3bhq2qfni44w"],
        type: "edge",
        properties: {},
      },
      {
        data: {
          duration: 2,
          path: "M 507.5 1276 507.5 1326,507.5 1326 705 1326,705 1326 705 1407",
        },
        id: "lehz20f3bhq2qfni44w->lehz1ojd5l6f0f8nfca-sink",
        source: "lehz20f3bhq2qfni44w",
        target: "lehz1ojd5l6f0f8nfca-sink",
        sources: ["lehz20f3bhq2qfni44w"],
        targets: ["lehz1ojd5l6f0f8nfca-sink"],
        type: "time-wait",
        properties: {},
      },
      {
        data: {
          duration: 2,
          path: "M 902.5 1276 902.5 1326,902.5 1326 705 1326,705 1326 705 1407",
        },
        id: "lehz1ygqjovg69f5bzh->lehz2271otslpq8u5p",
        source: "lehz1ygqjovg69f5bzh",
        target: "lehz2271otslpq8u5p",
        sources: ["lehz1ygqjovg69f5bzh"],
        targets: ["lehz2271otslpq8u5p"],
        type: "time-wait",
        properties: {},
      },
      {
        id: "lehz2271otslpq8u5p->lehz1ojd5l6f0f8nfca-sink",
        source: "lehz2271otslpq8u5p",
        target: "lehz1ojd5l6f0f8nfca-sink",
        sources: ["lehz2271otslpq8u5p"],
        targets: ["lehz1ojd5l6f0f8nfca-sink"],
        type: "edge",
        properties: {},
      },
    ],
  },
  {
    id: "root",
    children: [
      {
        id: "n1",
        ports: [
          {
            id: "e1:PORT:OUT",
            width: 1,
            x: -10,
            layoutOptions: {
              "elk.port.side": "SOUTH",
              "elk.port.index": 0,
            },
          },
        ],
        width: 150,
        height: 120,
      },
      {
        id: "grp_1",
        children: [
          {
            id: "n2",
            ports: [
              {
                id: "e1:PORT:IN",
                width: 1,
                x: 10,
                layoutOptions: {
                  "elk.port.side": "NORTH",
                  "elk.port.index": 1,
                },
              },
            ],
            width: 150,
            height: 120,
          },
        ],
        layoutOptions: {
          "elk.nodeSize.constraints": "MINIMUM_SIZE",
          "elk.nodeSize.minimum": "(200,0)",
          "elk.padding": "[top=40,right=10,bottom=40,left=10]",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        sources: ["e1:PORT:OUT"],
        targets: ["e1:PORT:IN"],
      },
    ],
    layoutOptions: {
      "elk.algorithm": "layered",
      "elk.direction": "DOWN",
      "elk.randomSeed": 117,
      "elk.spacing.nodeNode": 100,
      "elk.layered.spacing.nodeNodeBetweenLayers": 120,
      "elk.spacing.edgeEdge": 7,
      "elk.spacing.edgeNode": 10,
      "elk.spacing.edgeEdgeBetweenLayers": 7,
      "elk.spacing.portPort": 0,
      "elk.portConstraints": "FIXED_ORDER",
      "elk.portAlignment.default": "CENTER",
      "elk.port.side": "NORTH",
      "elk.spacing.componentComponent": 120,
      "elk.layered.layering.strategy": "COFFMAN_GRAHAM",
      "elk.layered.layering.coffmanGraham.layerBound": 4,
      "elk.layered.cycleBreaking.strategy": "DEPTH_FIRST",
      "elk.layered.crossingMinimization.strategy": "LAYER_SWEEP",
      "elk.layered.nodePlacement.strategy": "NETWORK_SIMPLEX",
      "elk.layered.nodePlacement.favorStraightEdges": true,
      "elk.layered.nodePlacement.bk.edgeStraightening": "IMPROVE_STRAIGHTNESS",
      "elk.layered.considerModelOrder.strategy": "NODES_AND_EDGES",
      edgeRouting: "ORTHOGONAL",
      hierarchyHandling: "INCLUDE_CHILDREN",
    },
  },
];
